### PR TITLE
Redo discard pile close button

### LINKED ISSUE #71: Improve Close Button When Viewing Discard Pile
From Alex: "In my head I'd imagined we'd pass an empty list to the CardViewer and render our own close button - it'd give us more control over exactly where we want it / how to style it etc. Thinking that a static exit button might make more sense, given that the action isn't tied into the card currently being viewed in any way."

### PR DESCRIPTION
**Pull request by kilikfan**
Make the close button from the discard pile distinct and not swipe.

### CODE REVIEW

**Comment by ghost** [comment]
Uggggghh that render error was gross and ~impossible to debug. I played around with a bunch of things and narrowed it down to putting the `CardViewer` directly into a `Column` being the problem (I could remove the whole close button stuff and it still broke). In the end found [this issue](https://github.com/flutter/flutter/issues/17036) which suggested using an `Expanded`, which fixed it.

So you just want to replace the `CardViewer` with:

```
Expanded(child: CardViewer(discard, buttons)),
```

:relieved:

**Comment by ghost** [comment]
Had a couple of other random thoughts:

1) Could we reverse the list when in the discard view? I think it would feel more natural if the most recent card was shown first, and scrolling through took you back in time (more like how a discard pile would actually work). We could achieve this by just passing `state.discard.reversed`

2) The back button is a bit pesky, because it "feels" like it should just exit the discard view, but it exits the whole game :scream:  We might be able to override its behaviour by wrapping the DiscardView in a `WillPopScope` (like I did for the play page to trigger a music change). WDYT?

The alternative to 2) would be to change the approach entirely, so rather than using state to drive showing the discard view we do it directly (so pressing the pile actually does a full transition, using `Navigator.push`, and to go back to the game you hit the back button which would pop scope back to where you were). Advantages of this would be:

 - Simpler game_state (we could get rid of the `viewingDiscard` boolean)
 - Simpler play page (one less switch for what to show)
 - We get the back behaviour we want for free. 
 - We could change the title, so it's clear that you're viewing the discard.
 
So maybe this is what we should have done in the first place... :thinking: :facepalm:

**Comment by kilikfan** [comment]
Thanks, that fixed the crash and I agree reversing the sort order makes sense as you're most likely to want to see the card you just discarded, and work your way down through the pile, it mirrors how you would go through it in real life. I do agree with what you're saying with the back button does seem more logical for it to work that way. And would be nice to change the header title to say you're viewing the discard pile (maybe for scrying page too?).

**Comment by kilikfan** [comment]
I'm getting some scoping issues with watching the GameState (most recently on deck_state_panel) if I try and make the Discard page a new page. Looks to me like the fix is pass the state through properly everywhere, but I could be missing something.

**Review by ghost — APPROVED** [review]
:dart:

**Pull request merged**
